project_root: /app  # so that you can save files from the docker image
project_results_folder: run_dynamicme_results
project_name: 'sms_ddb' # change to your own project to avoid overwriting the demo results
model_file: FoldME_Ali_keff.pickle
output_file: dynamicme_output_sms_ddb.csv

T: 40 # 10 #simulation length (hours)
dt: 0.1 #time step (hours)
V: 0.25 # volume (Liters)
X0: 0.015 #mass (grams)

#initial media concentrations
c0_dict:
  glc__D_e: 23
  ac_e: 0.0

#Max Uptake Rates
LB_EX: -10
LB_O2: -20.0
LB_GLC: -2.5

#track media composition
tracked_metabolites: 
  - ac_p
  - glc__D_p

#track translation rates
tracked_translation_reactions: true
#track biomass composition
tracked_biomass_to_biomass_reactions: true
#track complex formation reactions
tracked_complex_formation_reactions: true


# usage : python3 run_dynamicme.py config.yaml
